include kitty-themes/themes/Galaxy.conf

font_family Hasklug Nerd Font
font_size 14.0
disable_ligatures never

tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol '!'

sync_to_monitor no
cursor_shape underline
remember_window_size yes
macos_quit_when_last_window_closed yes
